### ISSUE TITLE
On updated site, aeon request is flakey

### ISSUE THREAD

**Issue by GarrettArm** [lsulibraries/SirsiDynexFunctionalTests#8]
This page seems to always correctly create the "Request Item" links in the last column of the Available table.  On a test runner, it only sometimes creates those links.  The "test_aeonLink" test fails when the link isn't created.

That aeonReuest() code was from Sirsi.  I can't see an obvious reason for it's flakeyness on the updated server.

**Comment by davidcomeaux** [comment]
Hi Garrett, thanks for finding and reporting this problem. I'm wondering if this is related to the Detail Actions widget that Sirsi wrote for us. The Sirsi rep describes it in an email sent Friday, 2/27.  It says that the code in the Detail Actions widget is needed, but i don't see it enabled on the test profile. Did you move that code to the custom js file? If not, maybe just enabling that widget will help.

**Comment by davidcomeaux** [comment]
I just enabled that widget in the Detail Display on the test server's default profile. Can you test this again please?

**Comment by davidcomeaux** [comment]
I just looked at this on my phone and found that the Aeon widget is not working at all. I searched for "Gumbo", and found that items held in University Archives display with a "Place Hold"link on the mobile display instead of Request Item" as they do in the desktop view.

**Comment by GarrettArm** [comment]
conversation moved to:  https://trello.com/c/s2e5gifR
